version: "2"
services:
  jekyll:
      image: jekyll/jekyll:3.8
      command: jekyll serve --force_polling
      ports:
          - 4001:4001
      volumes:
          - .:/srv/jekyll
      environment:
        JEKYLL_UID: 1001
        JEKYLL_GID: 1001
